env:
  global:
    - DISPLAY=:99.0
addons:
  firefox: latest
  apt:
    packages:
      - chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
dist: trusty
language: node_js
node_js:
  - "9.8.0"
install:
  - npm install
  