env:
  global:
    - DISPLAY=:99.0
    - secure: "ZAqnCgr83JU6ZFGJAdZy7BvrhVvTVpDf5wFR3EjgSwwsB1iYwytooJF5P/+1YGegyqlr0Lbit4rR61S8lG79nILPTO1zmXKeZQ9lcDnBB02Yc1rB3kJlMfJTBcH1rpDuBn8IVDxgHEpgtR1tCXP5L8qTBeQN5+gQrY4LcHmUnUpjNmxjnFQPTazAPpDcD58Fsw4tJeel63KUCi9eS42GCI49MqJ/bwiWwmXvfMMpvkEo+FGoB1rqjkP+2XjgVQHp4mgnlLJgMTFb2/H6Al5i9syOuC32GRUNkyZ+G4DiHrhxFHYT0c+ydRaq7QCN8QOzzkwInZx+qPzjixJwjRsXQ1AQTZy4wUKJ8UWjx6h+k3sGQDmVxRMe3+8845ZGm2T9yj1o2CaX6KyMUr0Nx525NbRbKjG6eFAWzsBKCl73cEoCAgl/GzRpcnJa/8nz2WeH/sqCN96eHMjGR4FmOr4jOGtlgHaqYuUdzed+RcX+/sitAgs7eLa7302PfGB882u8VuUU2+ICX2KYWL82NKf9U0lX0xZx1Gh1VSzQzH2aiqOeI/OK2EBOmzXjFafVxRxGL+sJsfb7x4+XGzdczDcdIbmWQTh05yCcnh/idUcpDPz4/hGarVRt2dNqmE0i7QWcTW1WaxQMI7Hz4t2BSyqkXJnlqYeOe651YgCNrL2mavs="
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - chromium-browser
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64> ./cc-test-reporter
  - chmod +x ./cc-test-reporter
dist: trusty
language: node_js
node_js:
  - 9.8.0
install:
  - npm install
after_script:
  - "./cc-test-reporter format-coverage test/unit/coverage/lcov.info --input-type lcov"
  - "./cc-test-reporter upload-coverage -r $CODECLIMATE_REPO_TOKEN"
